name: Build docker image and publish to registry

on:
  push:
    branches:
      - release/*
  workflow_dispatch:

env:
  IMAGE_NAME: go-portfolio

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set version hash
        run: |
          export VERSION_HASH=$(echo "${{github.sha}}" | cut -c1-6)
          echo "VERSION_HASH=$VERSION_HASH" >> $GITHUB_ENV

      - name: Run npm install
        run: npm ci

      - name: Build CSS
        run: |
          export VERSION_HASH=${{ env.VERSION_HASH }}
          npm run build:css

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME --build-arg VERSION_HASH=${{ env.VERSION_HASH }}

      - uses: docker/login-action@v1
        with:
          registry: registry.savemybank.lt
          username: save-my-bank
          password: ${{ secrets.DOCKER_PASS }}

      - name: Push image to SaveMyBank Container Registry
        run: |
          IMAGE_ID=registry.savemybank.lt/$IMAGE_NAME

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "main" ] && VERSION=latest

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          echo VERSION_HASH=$VERSION_HASH

          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
