name: Deploy latest version to environment

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag to run (e.g. 0.6)'
        required: true
        default: 'latest'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Use latest docker image
        uses: appleboy/ssh-action@master
        with:
          host: savemybank.lt
          username: ${{ secrets.SSH_USER_NAME }}
          password: ${{ secrets.SSH_USER_PASS }}
          script: |
            cd /home/web/portfolio
            export DOCKER_TAG=${{ github.event.inputs.tag }}
            docker-compose pull portfolio
            docker-compose up -d
